app:
    version: v1.0
    routinenum: 8
rabbitmq:
        host: localhost
        port: 5672
        username: test
        password: test
        virtualhost: /
        exchange: test.queue.exchange
        queue: test.queue
        exchangetype: direct
        routingkey: test.queue.key
listener:
        -
                type: mysql
                host: localhost
                port: 3306
                username: test
                password: test
                db: test
                charset: utf8mb4
                table: user
                unikey: openid
        -
                type: mysql
                host: localhost
                port: 3306
                username: test
                password: test
                db: student
                charset: utf8mb4
                table: student_info
                unikey: openid
                ignore: [ unionid, ]
                fieldmap:
                        nick_name: stu_nick


