app:
    version: v1.0
    routinenum: 8
rabbitmq:
        host: localhost
        port: 5672
        username: test        
        password: test
        virtualhost: /
        exchange: 
        queue: test.queue
        exchangetype: topic
        routingkey: 
        durable: false
listener:
        -
                type: mysql
                host: localhost
                port: 3306
                username: test
                password: test
                db: test
                charset: utf8mb4
                table: user
                unikey: openid
        